// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtkOAZKSAU-gEqzGH8DdvK-3a4-Q2Za5c',
    appId: '1:462321759833:web:eb90b244907c3907bb2348',
    messagingSenderId: '462321759833',
    projectId: 'mynotebookapp',
    authDomain: 'mynotebookapp.firebaseapp.com',
    storageBucket: 'mynotebookapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnPjcKHjdr-lZxZ8dRv9nneGMynuuh2MM',
    appId: '1:462321759833:android:24967a7717a4224cbb2348',
    messagingSenderId: '462321759833',
    projectId: 'mynotebookapp',
    storageBucket: 'mynotebookapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhNlCPshohfYbHi889rV1s8HkjBHXjZHs',
    appId: '1:462321759833:ios:9baa430264e600e2bb2348',
    messagingSenderId: '462321759833',
    projectId: 'mynotebookapp',
    storageBucket: 'mynotebookapp.appspot.com',
    iosClientId: '462321759833-j9d50ctcnh1h296ru2ggfgfn512a9snd.apps.googleusercontent.com',
    iosBundleId: 'com.gyanapps.mynotebook',
  );
}
